lab_1/urls.py
from django.urls import re_path
from .views import index,message_post,table

app_name = 'lab_1'

#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^table', table, name='table'),
    re_path(r'^message_post', message_post, name='message_post'),
]

lab_2/urls.py
from django.urls import path
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
]

login/urls.py
from django.urls import re_path
from .views import my_view

app_name = 'login'

#url for app
urlpatterns = [
    re_path(r'^login', my_view, name='login')
]

my_experience/urls.py
from django.urls import re_path
from .views import index
#url for app
app_name = 'my_experience'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

my_portfolio/urls.py
from django.urls import re_path
from .views import index
#url for app
app_name = 'my_portfolio'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

my_skill/urls.py
from django.urls import re_path
from .views import index
#url for app

app_name = 'my_skill'

urlpatterns = [
    re_path(r'^$', index, name='index'),
]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path
from django.contrib import admin
from lab_1.views import index as index_lab1
from my_experience.views import index as index_my_experience
from my_skill.views import index as index_my_skill
from my_portfolio.views import index as index_my_portfolio
from lab_4.views import index as index_lab4


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^lab-2/', include('lab_2.urls')),
    re_path(r'^$', index_lab1, name='index'),
    re_path(r'^my_experience', index_my_experience, name='my_experience'),
    re_path(r'^my_portfolio', index_my_portfolio, name='my_portfolio'),
    re_path(r'^my_skill', index_my_skill, name='my_skill'),
    re_path(r'^lab-4/', index_lab4, name='lab4'),
    re_path(r'^', include('django.contrib.auth.urls')),
    re_path(r'^', include('login.urls'))

]

lab_1/models.py
from django.db import models
from django.utils import timezone

class Message(models.Model):
	name = models.CharField(max_length=27)
	email = models.EmailField()
	message = models.TextField()
	created_date = models.DateTimeField(default=timezone.localtime())
	
	def str (self):
		return self.message

lab_2/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

login/models.py
from django.db import models

# Create your models here.

my_experience/models.py
from django.db import models

# Create your models here.

my_portfolio/models.py
from django.db import models

# Create your models here.

my_skill/models.py
from django.db import models

# Create your models here.

lab_1/forms.py
from django import forms

class Message_Form(forms.Form):
	error_messages = {
		'required': 'Tolong isi input ini',
		'invalid': 'Isi input dengan email',
	}
	attrs = {
		'class': 'form-control'
	}
	name = forms.CharField(label='Nama', required=False, max_length=27, widget=forms.TextInput(attrs=attrs))
	email = forms.EmailField(required=False,widget=forms.EmailInput(attrs=attrs))
	message = forms.CharField(widget=forms.Textarea(attrs=attrs),
	required=True)

lab_1/views.py
from django.shortcuts import render, redirect
from datetime import datetime, date
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from django.contrib.auth import authenticate, login
# from whitenoise.django import DjangoWhiteNoise
from django.core.wsgi import get_wsgi_application

# application = get_wsgi_application()
# application = DjangoWhiteNoise(application)
# Enter your name here
mhs_name = 'Paulus Lestyo Adhiatma' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(2002, 3, 9) #TODO Implement this, format (Year, Month, Date)
npm = None # TODO Implement this
messages = Message.objects.all().values()



# Create your views here.

def index(request):
	response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
	response['message_form'] = Message_Form
	return render(request, 'index_lab1.html', response)

def table(request):
		response = {'name': 'Message'}
		response['message'] = messages
		if request.user.is_authenticated:
			return render(request, 'table.html', response)
		else:
			return redirect('login')

def calculate_age(birth_year):
	return curr_year - birth_year if birth_year <= curr_year else 0


def message_post(request):
	form = Message_Form(request.POST or None)
	if(request.method == 'POST' and form.is_valid()):
		response = {}
		response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
		response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
		response['message'] = request.POST['message']
		message = Message(name=response['name'], email=response['email'],
		message=response['message'])
		message.save()
		html ='form_result.html'
		return render(request, html, response)
	else:
		return HttpResponseRedirect('/')

lab_2/views.py
from django.shortcuts import render
from lab_1.views import mhs_name, birth_date

#TODO Implement
#Create a content paragraph for your landing page:
landing_page_content = ''

def index(request):
    response = {'name': mhs_name, 'content': landing_page_content}
    return render(request, 'index_lab2.html', response)

lab_4/views.py
from django.shortcuts import render
from django.core.wsgi import get_wsgi_application

	
mhs_title = 'Live Chat'
def index(request):
    response = {'name': mhs_title}
    return render(request, 'lab_4/templates/lab_4.html', response)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
# Create your views here.

def my_view(request):
	username = request.POST['username']
	password = request.POST['password']
	
	user = authenticate(request, username=username,password=password)
	if user is not None:
		if user.is_active:
			response = {}
			request.session['user'] = user.username
			response['username'] = user.username
			login(request, user)
			return render(request, 'registration/logged-in.html', response)
		
	else:
		return HttpResponse('403')

my_experience/views.py
from django.shortcuts import render
from django.core.wsgi import get_wsgi_application


mhs_title = 'My First Time Ngoding'
def index(request):
    response = {'name': mhs_title}
    return render(request, 'my_experience.html', response)

my_portfolio/views.py
from django.shortcuts import render
from django.core.wsgi import get_wsgi_application


mhs_title = 'My Portfolio'
def index(request):
    response = {'name': mhs_title}
    return render(request, 'my_portfolio.html', response)

my_skill/views.py
from django.shortcuts import render
from django.core.wsgi import get_wsgi_application

	
mhs_title = 'My Skill'
def index(request):
    response = {'name': mhs_title}
    return render(request, 'my_skill.html', response)

lab_1/templates/form_result.html
{% extends "layout/base.html" %}
{% block content %}

<div class="jumbotron text-center">
			<h1>Form Result</h1>
			<p> Pesan dari {{ name }} </p> 
		</div>

<!-- {% block title %}{% endblock %} -->
<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;- {{name}}
	by {{ email }}
</textarea>
{% endblock %}

lab_1/templates/index_lab1.html
{% extends "layout/base.html" %}
{% block content %}
	    {% load staticfiles %}
		<div class="jumbotron text-center">
			<h1>{{ name }}</h1>
			<p>NO LIFE IS ENOUGH</p> 
		</div>

		<section class="light-gray-bg padding-top-70 padding-bottom-70">
			<div class="container"> 
				<div class="row">
	    			<div class="col-md-3 col-md-offset-2"> 
		                <img src="{% static 'avatar.png' %}" alt="gambar" style="border-radius: 50%;height: 250px;width: 250px"> 
	            	</div>
	            	 
	            	<div class="col-md-6 text-justify"> <span class="date"></span>
	            		<h4>Lahir 9 Maret 2002 ({{ age }} years old)</h4>
					    <table>
		                    <tr>
		                      <td style="padding:5px">Alamat</td>
		                      <td style="padding:5px">: Beralamat di Jl. Makam Bergolo No. 19, RT.04 RW.08 Serengan, <br>&nbsp Serengan, Surakarta</td>
		                    </tr>
		                    <tr>
		                      <td style="padding:5px">Email</td>
		                      <td style="padding:5px">: email : lestyo24@gmail.com</td>
		                    </tr>
		                    <tr>
		                      <td style="padding:5px">Kontak</td>
		                      <td style="padding:5px">: 089667259831</td>
		                    </tr>
		                  </table>
		                  <br>
	            		<p>Perkenalkan nama saya adalah <b>{{ name }}</b>. Sebut saja saya seorang programmer dari SMK N 2 Surakarta yang saat ini sedang menjalani praktek kerja industri di <a href="http://www.duxeos.com" target="_blank">Duxeos Software House</a>. Saya masih sangat membutuhkan ilmu pengetahuan tetang programming baik itu dibidang bahasa pemrograman maupun wawasan tentang pemrograman.</p>
	            	</div>

				</div>
			</div>
		</section>
		
		<div class="col-md-2"> 
	    </div>
	    <div class="col-md-8"> 
	    
		<section name="form">
			<h2>Send Message</h2>
			
			<form id="form" method="POST" action="{% url 'lab_1:message_post' %}">
			{% csrf_token %}
			{{ message_form }}
			<br>
			<button type="submit" class="btn btn-default">Submit</button><br>
			</form>
		</section>
		<br><br>
		</div>

		<div class="col-md-2"> 
	    </div>
	    <div style="clear: both;"></div>
{% endblock %}

lab_1/templates/layout/base.html
<!DOCTYPE html>
{% include "partials/header.html" %}

{% block content %} {% endblock %}

{% include "partials/footer.html" %}

lab_1/templates/partials/footer.html
	<footer style="padding: 25px 0;text-align: center;color: rgba(255,255,255,.3);background-color: #222;">
	<p> &copy; Paulus Lestyo Adhiatma </p>
	</footer>
	</div>
	{% load staticfiles %}
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'js/lab_4.js' %}"></script>
</body>
</html>

lab_1/templates/partials/header.html
<!-- {% block header %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="{% static 'css/lab_4.css' %}" />
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
</head>
<body>
	<div id="content"> 
		<nav class="navbar navbar-default" style="margin-bottom: 0;">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="#">Portfolio</a>
		    </div>
		    <ul class="nav navbar-nav">
		      <li><a href="{% url 'index' %}">Home</a></li>
		      <li><a href="{% url 'my_skill' %}">My Skill</a></li>
		      <li><a href="{% url 'my_portfolio' %}">My Portfolio</a></li>
		      <li><a href="{% url 'my_experience' %}">My Experience</a></li>
		      <li><a href="{% url 'lab_1:table' %}">Message</a></li>
		      <li><a href="{% url 'lab4' %}">Live Chat</a></li>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
	    	  {% if request.session.user %}
		      <li><a href="{% url 'logout' %}">Logout</a></li>
		      {% else %}
		      <li><a href="{% url 'login' %}">Login</a></li>
		      {% endif %}
		    </ul>
		  </div>
		</nav>
<!-- {% endblock %} -->

lab_1/templates/table.html
{% extends "layout/base.html" %}
{% block content %}

<!-- Populate semua isi pesan dari model -->
<div class="jumbotron text-center">
			<h1>{{ name }}</h1>
			<p>Welcome Admin {{ request.session.user }}!</p>
		</div>
<table class="table">
	<thead>
		<th>Nama</th>
		<th>Email</th>
		<th>Pesan</th>
		<th>Dibuat Pada</th>
	</thead>

	<tbody>
	<!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
		{% for i in message %}
		{% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
		<tr class="warning"> {% else %} <tr class="success">
			{% endif %}
			<td> {{i.name}} </td>
			<td> {{i.email}} </td>
			<td> {{i.message}} </td>
			<td> {{i.created_date}} </td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

lab_4/templates/lab_4/layouts/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="description" content="LAB 4">
<meta name="author" content="{{author}}">
<!-- bootstrap csss -->
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'css/lab_4.css' %}" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css" rel="stylesheet" />
<title>
{% block title %} Lab 4 By Paul {% endblock %}
</title>
</head>
<body>
<header>
{% include "lab_4/partials/header.html" %}
</header>
<content>
{% block content %}
<!-- content goes here -->
{% endblock %}
</content>
<footer>
<!-- TODO Block Footer dan include footer.html -->
{% block footer %}
{% include "lab_4/partials/footer.html" %}
{% endblock %}
</footer>
<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
			selectedTheme = JSON.parse(localStorage.selectedTheme);
			$('body').css('background-color',selectedTheme.bcgColor);
			$('.apply-button').css('color',selectedTheme.fontColor);
	});
</script>
<script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js "></script>
<script src="{% static 'js/lab_4.js' %}"></script>
</body>

lab_4/templates/lab_4/partials/header.html
<!-- {% block header %} -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ name }}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
	<div id="content"> 
		<nav class="navbar navbar-default" style="margin-bottom: 0">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="#">Portfolio</a>
		    </div>
		    <ul class="nav navbar-nav">
		      <li><a href="{% url 'index' %}">Home</a></li>
		      <li><a href="{% url 'my_skill' %}">My Skill</a></li>
		      <li><a href="{% url 'my_portfolio' %}">My Portfolio</a></li>
		      <li><a href="{% url 'my_experience' %}">My Experience</a></li>
		      <li><a href="{% url 'lab_1:table' %}">Message</a></li>
		      <li><a href="{% url 'lab4' %}">Live Chat</a></li>
		    </ul>
		  </div>
		</nav>
<!-- {% endblock %} -->

lab_4/templates/lab_4/templates/lab_4.html
{% extends "lab_4/layouts/base.html" %}
{% block content %}
<!-- ChatBox Section -->
<section name="Chatbox">
	<div class="wrapper">
		<div class="col-md-3">
			<select class="my-select" style="width: 150px;">
			</select>
			<button class="apply-button">apply</button>
		</div>

		<div class="chat-box">
			<div class="chat-head">
				<h2>Chat</h2>
				<img id="Expand-Arrow" src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_down-16.png" title="Expand Arrow" width="16"  style="display: none;">
				<img id="Expand-Arrow-Up" src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_up-16.png" title="Expand Arrow" width="16"">
			</div>
			<div class="chat-body">
				<div class="msg-insert">
				</div>
				<div class="chat-text">
					<textarea id="text" placeholder="Press Enter"></textarea>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

my_experience/templates/my_experience.html
{% extends "layout/base.html" %}
{% block content %}
	    {% load staticfiles %}
		<div class="jumbotron text-center">
			<h1>{{ name }}</h1>
		</div>

		<section class="light-gray-bg padding-top-70 padding-bottom-70">
			<div class="container"> 
				<div class="row">
	    			<div class="col-md-3"></div>

	            	<div class="col-md-6 text-justify">
	            		<!-- <div class="text-center"> <img src="{% static 'avatar.png' %}" alt="gambar" style="border-radius: 20%;height: 250px;width: 250px"> 
	            		</div> -->

	            		<p style="text-indent: 50px">Setiap orang pasti memiliki kesan hal yang pertama mereka lakukan, termasuk juga dengan pertama kali ngoding. Sebelum saya masuk di Sekolah Menengah Kejuruan(SMK) Negeri 2 Surakarta dengan Jurusan Rekayasa Perangkat Lunak(RPL) saya sudah mencoba-coba untuk ngoding menggunakan laptop saya dan bahasa pemrograman yang saya coba pertama kali yaitu bahasa pemorgraman html.</p>
	            		<div class="text-center"> <img src="{% static 'img/belajar.png' %}" alt="gambar" style="height: 250px;"> 
	            		</div>
	            		<br>
	            		<p style="text-indent: 50px">Saat ngoding pertama kali itu saya tidak ngoding sendiri dari awal, melaikan copas dari tutorial yang diberikan oleh teman saya. Walaupun hanya copas dari tutorial tapi ketika saya jalankan di browser dan berjalan dengan lancar, saya sangat senang sekali. Dan itulah pertama kalinya saya ngoding.</p>
	            	</div>

	            	<div class="col-md-3"></div>

				</div>
			</div>
		</section>
	


{% endblock %}

my_portfolio/templates/my_portfolio.html
{% extends "layout/base.html" %}
{% block content %}
	    {% load staticfiles %}
	    
		<div class="jumbotron text-center">
			<h1>{{ name }}</h1>
		</div>


		<section class="light-gray-bg padding-top-70 padding-bottom-70">
			<div class="container"> 
				<div class="row">
	    			<div class="col-md-2"> 
	            	</div> 	 
	            	<div class="col-md-8 text-center"> <span class="date"></span>

	      <h3>Wonderful Indonesia</h3>
	      <div id="myCarousel" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousel" data-slide-to="1"></li>
		    <li data-target="#myCarousel" data-slide-to="2"></li>
		    <li data-target="#myCarousel" data-slide-to="3"></li>
		    <li data-target="#myCarousel" data-slide-to="4"></li>
		    <li data-target="#myCarousel" data-slide-to="5"></li>
		  </ol>

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" style="height: 400px">
		    <div class="item active" style="height: 100%;width: 100%;">
		      <img src="{% static 'img/1.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/2.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/3.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/4.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/5.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/6.png' %}" style="height: 100%;width: 100%;">
		    </div>
		  </div>

		  <!-- Left and right controls -->
		  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousel" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
		<p>Website diatas adalah sebuah website bertemakan keindahan indonesia yang dibuat oleh tim yang beranggotakan 3 orang termasuk saya. Untuk Lomba Web Design IT Fest 2018 yang diadakan oleh UNS dan tidak disangka mendapatkan juara 3.</p>
		<br><br>

		<h3>Interior Design With CodeIgniter</h3>
	      <div id="myCarousels" class="carousel slide" data-ride="carousel">
		  <!-- Indicators -->
		  <ol class="carousel-indicators">
		    <li data-target="#myCarousels" data-slide-to="0" class="active"></li>
		    <li data-target="#myCarousels" data-slide-to="1"></li>
		    <li data-target="#myCarousels" data-slide-to="2"></li>
		    <li data-target="#myCarousels" data-slide-to="3"></li>
		    <li data-target="#myCarousels" data-slide-to="4"></li>
		    <li data-target="#myCarousels" data-slide-to="5"></li>
		  </ol>

		  <!-- Wrapper for slides -->
		  <div class="carousel-inner" style="height: 400px">
		    <div class="item active" style="height: 100%;width: 100%;">
		      <img src="{% static 'img/inteco1.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/inteco2.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/inteco3.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/inteco4.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/inteco5.png' %}" style="height: 100%;width: 100%;">
		    </div>
		    <div class="item" style="height: 100%;width: 100%;">
		      <img src="{% static '/img/inteco6.png' %}" style="height: 100%;width: 100%;">
		    </div>
		  </div>

		  <!-- Left and right controls -->
		  <a class="left carousel-control" href="#myCarousels" data-slide="prev">
		    <span class="glyphicon glyphicon-chevron-left"></span>
		    <span class="sr-only">Previous</span>
		  </a>
		  <a class="right carousel-control" href="#myCarousels" data-slide="next">
		    <span class="glyphicon glyphicon-chevron-right"></span>
		    <span class="sr-only">Next</span>
		  </a>
		</div>
		<p>Website yang satu ini saya buat dengan menggunakan Framework PHP Codeigniter dan template css yang saya download di internet yang sudah saya edit sesuai keinginan saya.</p>
					    
	            	</div>
	            	<div class="col-md-2"> 
	            	</div>

				</div>
			</div>
		</section>

		<section name="Chatbox">
			<div class="wrapper">
				<div class="chat-box">
					<div class="chat-head">
						<h2>Chat</h2>
						<img id="Expand-Arrow" src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_down-16.png" title="Expand Arrow" width="16" style="display: none;">
						<img id="Expand-Arrow-Up" src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_up-16.png" title="Expand Arrow" width="16">
					</div>
					<div class="chat-body">
						<div class="msg-insert">
						</div>
						<div class="chat-text">
							<textarea id="text" placeholder="Press Enter"></textarea>
						</div>
					</div>
				</div>
			</div>
		</section>
	

{% endblock %}

my_skill/templates/my_skill.html
{% extends "layout/base.html" %}
{% block content %}
	    {% load staticfiles %}
	    
		<div class="jumbotron text-center">
			<h1>{{ name }}</h1>
		</div>

		<section class="light-gray-bg padding-top-70 padding-bottom-70">
			<div class="container"> 
				<div class="row">
	            	<div class="col-md-6 text-justify"> <span class="date"></span>
	            		<h1 class="text-center">Basic</h1>
	            		<h4>HTML</h4>
	            		 <div class="progress">
							  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
					  		  aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%">
					  		  </div>
						</div>
						<h4>CSS | CSS3</h4>	
						<div class="progress">
						  <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar"
						  aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width:80%">
						  </div>
						</div>
						<h4>Javascript</h4>
						<div class="progress">
						  <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar"
						  aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:60%">
						  </div>
						</div>
						<h4>Python</h4>
						<div class="progress">
						  <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar"
						  aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%">
						  </div>
						</div> 

	            	</div>
	            	<div class="col-md-6 text-justify"> <span class="date"></span>
	            		<h1 class="text-center">Framework</h1>
	            		<h4>CodeIgniter</h4>
	            		 <div class="progress">
							  <div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar"
					  		  aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width:90%">
					  		  </div>
						</div>
						<h4>Laravel</h4>	
						<div class="progress">
						  <div class="progress-bar progress-bar-info progress-bar-striped active" role="progressbar"
						  aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:60%">
						  </div>
						</div>
						<h4>Django</h4>
						<div class="progress">
						  <div class="progress-bar progress-bar-warning progress-bar-striped active" role="progressbar"
						  aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width:60%">
						  </div>
						</div>
						<h4>Bootstrap</h4>
						<div class="progress">
						  <div class="progress-bar progress-bar-danger progress-bar-striped active" role="progressbar"
						  aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:70%">
						  </div>
						</div> 

				</div>
			</div>
		</section>
	


{% endblock %}